-- Postgres version of schema.sql (for Supabase)
-- How to use:
--   1. Open https://supabase.com/dashboard/project/kmyewmtcqlbxgfymnahi/sql
--   2. Paste this whole file into the query editor
--   3. Click "Run" (the file contains only CREATE TABLE statements, safe to run twice)
--   4. Then run the server, which auto-creates the default admin user (admin / admin123)

-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role TEXT NOT NULL DEFAULT 'student' CHECK (role IN ('student','admin','warden')),
  status SMALLINT NOT NULL DEFAULT 1,
  approved SMALLINT NOT NULL DEFAULT 0,
  approved_by BIGINT DEFAULT NULL,
  approved_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_users_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS password_resets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token VARCHAR(255) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_password_resets_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  roll_no VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  gender TEXT NOT NULL DEFAULT 'Male' CHECK (gender IN ('Male','Female','Other')),
  course VARCHAR(100) DEFAULT NULL,
  year VARCHAR(50) DEFAULT NULL,
  guardian_name VARCHAR(255) DEFAULT NULL,
  guardian_phone VARCHAR(20) DEFAULT NULL,
  admission_date DATE DEFAULT NULL,
  join_date DATE DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Inactive')),
  hostel_type TEXT CHECK (hostel_type IN ('boys','girls')),
  CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS wardens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  shift VARCHAR(50) DEFAULT NULL,
  hostel_type TEXT DEFAULT NULL CHECK (hostel_type IN ('boys','girls')),
  status SMALLINT NOT NULL DEFAULT 1,
  CONSTRAINT fk_wardens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_no VARCHAR(20) NOT NULL,
  floor INT DEFAULT NULL,
  room_type VARCHAR(50) DEFAULT NULL,
  hostel_type TEXT DEFAULT NULL CHECK (hostel_type IN ('boys','girls')),
  capacity INT NOT NULL DEFAULT 1,
  occupancy INT NOT NULL DEFAULT 0,
  fee_per_month NUMERIC(10,2) DEFAULT 0,
  description TEXT DEFAULT NULL,
  status TEXT NOT NULL DEFAULT 'Available' CHECK (status IN ('Available','Full','Maintenance'))
);

CREATE TABLE IF NOT EXISTS room_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  bed_no VARCHAR(10) DEFAULT NULL,
  allocation_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','CheckedOut')),
  checkout_date DATE DEFAULT NULL,
  CONSTRAINT fk_alloc_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_alloc_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS fees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  total_fee NUMERIC(10,2) NOT NULL DEFAULT 0,
  paid_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  due_amount NUMERIC(10,2) DEFAULT 0,
  payment_mode VARCHAR(50) DEFAULT NULL,
  receipt_no VARCHAR(100) DEFAULT NULL,
  payment_date TIMESTAMPTZ DEFAULT NULL,
  utr VARCHAR(100) DEFAULT NULL,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Paid','Partial')),
  CONSTRAINT fk_fees_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS complaints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  title VARCHAR(255) NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low','Medium','High','Critical')),
  status VARCHAR(50) DEFAULT 'Pending',
  admin_response TEXT DEFAULT NULL,
  resolved_by BIGINT DEFAULT NULL,
  resolved_at TIMESTAMPTZ DEFAULT NULL,
  resolution_date TIMESTAMPTZ DEFAULT NULL,
  resolution_notes TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_complaints_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_complaints_resolved_by FOREIGN KEY (resolved_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS complaint_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  complaint_id BIGINT NOT NULL,
  action VARCHAR(255) DEFAULT NULL,
  performed_by BIGINT DEFAULT NULL,
  role VARCHAR(50) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_complaint_logs_complaint FOREIGN KEY (complaint_id) REFERENCES complaints(id) ON DELETE CASCADE,
  CONSTRAINT fk_complaint_logs_user FOREIGN KEY (performed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  reason TEXT DEFAULT NULL,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Approved','Rejected')),
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  warden_id BIGINT DEFAULT NULL,
  approved_by BIGINT DEFAULT NULL,
  admin_remark TEXT DEFAULT NULL,
  CONSTRAINT fk_leaves_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_leaves_warden FOREIGN KEY (warden_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_leaves_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Present','Absent')),
  remarks TEXT DEFAULT NULL,
  taken_by BIGINT DEFAULT NULL,
  taken_role VARCHAR(50) DEFAULT NULL,
  is_locked SMALLINT NOT NULL DEFAULT 0,
  time TIMESTAMPTZ DEFAULT NULL,
  CONSTRAINT unique_attendance UNIQUE (student_id, date),
  CONSTRAINT fk_attendance_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_attendance_taken_by FOREIGN KEY (taken_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  priority VARCHAR(50) DEFAULT 'Normal',
  target_role VARCHAR(50) DEFAULT 'all',
  publish_date DATE DEFAULT NULL,
  expiry_date DATE DEFAULT NULL,
  expires_at TIMESTAMPTZ DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_notices_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS mess_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day VARCHAR(20) NOT NULL,
  meal_type VARCHAR(50) NOT NULL,
  menu_items TEXT NOT NULL,
  date DATE DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS hostel_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  event_date DATE DEFAULT NULL,
  event_time VARCHAR(50) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_by BIGINT DEFAULT NULL,
  CONSTRAINT fk_events_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS visitor_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visitor_name VARCHAR(255) NOT NULL,
  contact VARCHAR(20) DEFAULT NULL,
  purpose VARCHAR(255) DEFAULT NULL,
  student_id BIGINT DEFAULT NULL,
  check_in TIMESTAMPTZ DEFAULT NULL,
  check_out TIMESTAMPTZ DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  warden_approved SMALLINT DEFAULT 0,
  created_by BIGINT DEFAULT NULL,
  CONSTRAINT fk_visitor_logs_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL,
  CONSTRAINT fk_visitor_logs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS management_staff (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  designation VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  icon VARCHAR(255) DEFAULT NULL,
  sort_order INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS vacated_students (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  original_id BIGINT DEFAULT NULL,
  original_user_id BIGINT DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  roll_no VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  gender VARCHAR(20) DEFAULT NULL,
  course VARCHAR(100) DEFAULT NULL,
  year VARCHAR(50) DEFAULT NULL,
  guardian_name VARCHAR(255) DEFAULT NULL,
  guardian_phone VARCHAR(20) DEFAULT NULL,
  admission_date DATE DEFAULT NULL,
  join_date DATE DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  last_room_no VARCHAR(20) DEFAULT NULL,
  vacate_reason TEXT DEFAULT NULL,
  admin_remark TEXT DEFAULT NULL,
  related_data JSONB DEFAULT NULL,
  vacated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS room_maintenance_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT NOT NULL,
  problem TEXT DEFAULT NULL,
  solution TEXT DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  completed_by VARCHAR(255) DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  cost NUMERIC(10,2) DEFAULT 0,
  repair_date DATE DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  CONSTRAINT fk_maintenance_history_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_maintenance_history_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS maintenance_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT DEFAULT NULL,
  room_id BIGINT DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  priority TEXT NOT NULL DEFAULT 'Medium' CHECK (priority IN ('Low','Medium','High','Emergency')),
  status VARCHAR(50) DEFAULT 'Pending',
  assigned_to BIGINT DEFAULT NULL,
  assigned_date TIMESTAMPTZ DEFAULT NULL,
  completed_date TIMESTAMPTZ DEFAULT NULL,
  completion_remarks TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_maint_req_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL,
  CONSTRAINT fk_maint_req_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL,
  CONSTRAINT fk_maint_req_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS room_change_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  current_room_id BIGINT DEFAULT NULL,
  requested_room_id BIGINT DEFAULT NULL,
  reason TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  admin_remark TEXT DEFAULT NULL,
  CONSTRAINT fk_room_change_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_room_change_current FOREIGN KEY (current_room_id) REFERENCES rooms(id) ON DELETE SET NULL,
  CONSTRAINT fk_room_change_requested FOREIGN KEY (requested_room_id) REFERENCES rooms(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS emergency_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  category VARCHAR(100) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  priority TEXT NOT NULL DEFAULT 'High' CHECK (priority IN ('Low','Medium','High','Critical')),
  status VARCHAR(50) DEFAULT 'Open',
  assigned_to BIGINT DEFAULT NULL,
  resolution TEXT DEFAULT NULL,
  resolved_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_emergency_reports_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_emergency_reports_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS emergency_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emergency_id BIGINT DEFAULT NULL,
  student_id BIGINT DEFAULT NULL,
  severity VARCHAR(50) DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  reported_at TIMESTAMPTZ DEFAULT NULL,
  response_notes TEXT DEFAULT NULL,
  responded_by BIGINT DEFAULT NULL,
  responded_at TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_emergency_logs_report FOREIGN KEY (emergency_id) REFERENCES emergency_reports(id) ON DELETE SET NULL,
  CONSTRAINT fk_emergency_logs_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL,
  CONSTRAINT fk_emergency_logs_responded_by FOREIGN KEY (responded_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS vacate_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  reason TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  admin_remark TEXT DEFAULT NULL,
  CONSTRAINT fk_vacate_requests_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  subject VARCHAR(255) DEFAULT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS student_digital_ids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL UNIQUE,
  id_number VARCHAR(50) NOT NULL,
  blood_group VARCHAR(10) DEFAULT NULL,
  emergency_contact VARCHAR(20) DEFAULT NULL,
  emergency_name VARCHAR(255) DEFAULT NULL,
  CONSTRAINT fk_digital_ids_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS backup_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  filepath VARCHAR(500) DEFAULT NULL,
  filesize BIGINT DEFAULT 0,
  type VARCHAR(50) DEFAULT 'manual',
  created_by BIGINT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_backup_history_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS night_roll_call (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  date DATE NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Present','Absent')),
  remarks TEXT DEFAULT NULL,
  marked_by BIGINT DEFAULT NULL,
  marked_at TIMESTAMPTZ DEFAULT NULL,
  CONSTRAINT unique_roll_call UNIQUE (student_id, date),
  CONSTRAINT fk_roll_call_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_roll_call_marked_by FOREIGN KEY (marked_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS room_inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT NOT NULL,
  inspector_id BIGINT DEFAULT NULL,
  inspection_date DATE DEFAULT NULL,
  cleanliness_rating INT DEFAULT NULL,
  maintenance_notes TEXT DEFAULT NULL,
  action_taken TEXT DEFAULT NULL,
  CONSTRAINT fk_inspections_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_inspections_inspector FOREIGN KEY (inspector_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS medical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  reported_by BIGINT DEFAULT NULL,
  symptoms TEXT DEFAULT NULL,
  diagnosis TEXT DEFAULT NULL,
  treatment TEXT DEFAULT NULL,
  medication TEXT DEFAULT NULL,
  follow_up_date DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_medical_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_medical_reported_by FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS discipline_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT NOT NULL,
  reported_by BIGINT DEFAULT NULL,
  incident_type VARCHAR(100) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  severity VARCHAR(50) DEFAULT NULL,
  action_taken TEXT DEFAULT NULL,
  remarks TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_discipline_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_discipline_reported_by FOREIGN KEY (reported_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  message TEXT DEFAULT NULL,
  is_read SMALLINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS visitors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id BIGINT DEFAULT NULL,
  name VARCHAR(255) DEFAULT NULL,
  purpose VARCHAR(255) DEFAULT NULL,
  entry_time TIMESTAMPTZ DEFAULT NULL,
  CONSTRAINT fk_visitors_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  rating INT DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS faq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT DEFAULT NULL,
  answer TEXT DEFAULT NULL,
  sort_order INT DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1
);